set wt [gi::getWindowTypes seSymbol]
db::setAttr wt.geometry -value "1632x947+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes giConsole]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes leLayout]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes seSchematic]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes deBookmarkManager]
db::setAttr wt.geometry -value "530x400"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes dbFindReplace]
db::setAttr wt.geometry -value "580x620"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtJobMonitor]
db::setAttr wt.geometry -value "800x600+55+105"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes xtTextViewer]
db::setAttr wt.geometry -value "1430x756+245+142"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedResultsViewer]
db::setAttr wt.geometry -value "1024x768+105+155"
db::setAttr wt.maximized -value "false"
set wt [gi::getWindowTypes embedWaveViewer]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
set wt [gi::getWindowTypes saConsoleHSPICE]
db::setAttr wt.geometry -value "1910x1020+5+55"
db::setAttr wt.maximized -value "true"
unset wt
