::sa::_backgroundSaeShell::signalProcessReady 1713230848 75160
::wf::updateViewerLicense 2
::wf::updateViewerLicense 2
::sa::_backgroundSaeShell::runScript /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/bg_script.tcl 0 sa::_testSuite::netlistAndRun::structNetlistingDone scriptDir /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic testSuiteName saeSession9 cmdArgs {default 1 1 0 1 0} taskId 9 isReRun 1
db::setAttr geometry -of [gi::getFrames 1] -value 1014x710+5+52
::sa::_backgroundSaeShell::runScript /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/bg_script.tcl 0 sa::_testSuite::netlistAndRun::structNetlistingDone scriptDir /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic testSuiteName saeSession9 cmdArgs {default 1 1 0 1 0} taskId 10 isReRun 1
::sa::_backgroundSaeShell::runScript /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal/.bg_measurement_script.tcl 0 sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession9 uniqueSessionName {} testbenchName default resultsDir /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal/results testSuiteDir /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal databaseName /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/bg_script.tcl 0 sa::_testSuite::netlistAndRun::structNetlistingDone scriptDir /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic testSuiteName saeSession9 cmdArgs {default 1 1 0 1 0} taskId 11 isReRun 1
::sa::_backgroundSaeShell::runScript /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal/.bg_measurement_script.tcl 0 sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession9 uniqueSessionName {} testbenchName default resultsDir /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal/results testSuiteDir /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal databaseName /home/Cordero_Matamoros_I_2024_vlsi/simulation/tarea_2,compleja,schematic/history_1/simulation/default/FineSimProVCS/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::wf::viewerExited
::wf::updateViewerLicense 2
::sa::_backgroundSaeShell::exit
